#ifndef EMVTAGS_H
#define EMVTAGS_H

enum
{
  EMV_TAG_APPLICATION_IDENTIFIER                   = 0x4F,
  EMV_TAG_APPLICATION_LABEL                        = 0x50,
  EMV_TAG_TRACK_1_EQUIVALENT_DATA          				 = 0x56,
  EMV_TAG_TRACK_2_EQUIVALENT_DATA                  = 0x57,
  EMV_TAG_PRIMARY_ACCCOUNT_NUMBER                  = 0x5A,
  TAG_EMV_ISSUER_SCRIPT_TEMPLATE_1                 = 0x71,
  TAG_EMV_ISSUER_SCRIPT_TEMPLATE_2                 = 0x72,
  EMV_TAG_APPLICATION_INTERCHANGE_PROFILE          = 0x82,
  EMV_TAG_DEDICATED_FILE_NAME                      = 0x84,
  EMV_TAG_AUTHORIZATION_CODE                       = 0x89,
  TAG_EMV_AUTHORIZATION_RESPONSE_CODE              = 0x8A,
  TAG_EMV_CVM_LIST									= 0x8E,
  TAG_EMV_CERT_AUTH_PUBLIC_KEY_INDEX			   			 = 0x8F,
  TAG_EMV_ISSUER_AUTHENTICATION_DATA               = 0x91,
  EMV_TAG_TERMINAL_VERIFICATION_RESULTS            = 0x95,
  EMV_TAG_TRANSACTION_DATE                         = 0x9A,
  EMV_TRANSACTION_STATUS_INFORMATION               = 0x9B,
  EMV_TAG_TRANSACTION_TYPE                         = 0x9C,
  EMV_TAG_CARDHOLDER_NAME                          = 0x5F20,
  EMV_TAG_LANGUAGE_PREFERENCE                      = 0x5F2D,
  EMV_TAG_ISSUER_COUNTRY_CODE											 = 0x5F28,
  EMV_TAG_TRANSACTION_CURRENCY_CODE                = 0x5F2A,
  EMV_TAG_APPLICATION_PAN_SEQUENCE_NUMBER          = 0x5F34,
  EMV_TAG_AMOUNT_AUTHORIZED_NUMERIC                = 0x9F02,
  EMV_TAG_AMOUNT_OTHER_NUMERIC						= 0x9F03,
  EMV_TAG_APPLICATION_IDENTIFIER_TERMINAL          = 0x9F06,
  EMV_TAG_ICC_APPLICATION_VERSION_NUMBER           = 0x9F08,
  EMV_TAG_TERM_APPLICATION_VERSION_NUMBER          = 0x9F09,
  EMV_TAG_ISSUER_APPLICATION_DATA                  = 0x9F10,
  EMV_TAG_IAC_DEFAULT								= 0x9F0D,
  EMV_TAG_IAC_DENIAL								= 0x9F0E,
  EMV_TAG_IAC_ONLINE			                    = 0x9F0F,
  EMV_TAG_TAC_DEFAULT								= 0xDF14,
  EMV_TAG_TAC_DENIAL								= 0xDF15,
  EMV_TAG_TAC_ONLINE			                    = 0xDF16,

  EMV_TAG_ISSUER_CODE_TABLE_INDEX                  = 0x9F11,
  EMV_TAG_APPLICATION_PREFERRED_NAME               = 0x9F12,
  EMV_MERCHANT_IDENTIFIER                          = 0x9F16,
  EMV_CHECK_TRY_PIN_TIME                           = 0x9F17,
  EMV_TERMINAL_COUNTRY_CODE                        = 0x9F1A,
  EMV_TERMINAL_RISK_MANAGEMENT_DATA                = 0x9F1D,
  EMV_TAG_TRANSACTION_TIME												 = 0x9F21,
  EMV_TAG_APPLICATION_CRYPTOGRAM                   = 0x9F26,
  EMV_TAG_CRYPTOGRAM_INFORMATION_DATA              = 0x9F27,
  EMV_TAG_TERMINAL_CAPABILITIES                    = 0x9F33,  
  EMV_TAG_CARDHOLDER_VERIFICATION_METHOD_RESULTS   = 0x9F34,
  EMV_TAG_TERMINAL_TYPE                            = 0x9F35,
  EMV_TAG_APPLICATION_TRANSACTION_COUNTER          = 0x9F36,
  EMV_TAG_UNPREDICTABLE_NUMBER                     = 0x9F37,
  EMV_TAG_POS_ENTRY_MODE_CODE                      = 0x9F39,
  EMV_TAG_TRANSACTION_SEQ_COUNTER                  = 0x9F41,
  EMV_TAG_SIGNED_DYNAMIC_APPLICATION_DATA					 = 0X9F4B,
  EMV_TAG_CARD_AUTHENTICATION_RELATED_DATA         = 0x9F69,
  EMV_TAG_MSR_TRACK2															 = 0x9F6B,
  EMV_TAG_CARD_TRANSACTION_QUALIFIER               = 0x9F6C,

  EMV_TAG_ISSUER_SCRIPT_RESULTS                    = 0xDF11,
  EMV_TAG_AUTHORIZATION_RESPONSE_CODE_LIST         = 0xDF16,
  EMV_TAG_POSSIBLE_TRANSACTION_TYPES               = 0xDF3A,
  EMV_TAG_CTLS_C0																	 = 0xC0,
  EMV_TAG_CTLS_C1																	 = 0xC1,
  EMV_TAG_CTLS_C2																	 = 0xC2,
  EMV_TAG_CTLS_C3																	 = 0xC3,
  EMV_TAG_CTLS_C4																	 = 0xC4,
  EMV_TAG_CTLS_C5																	 = 0xC5,
  EMV_TAG_CTLS_C6																	 = 0xC6,
  EMV_TAG_CTLS_C7																	 = 0xC7,
  EMV_TAG_CTLS_C8																	 = 0xC8,
  EMV_TAG_CTLS_C9																	 = 0xC9,
  EMV_TAG_CTLS_D1																	 = 0xD1,	// track 1
  EMV_TAG_CTLS_D2																	 = 0xD2,	// track 2
  EMV_TAG_CTLS_E0															     = 0xE0,
  EMV_TAG_CTLS_E2																	 = 0xE2,	
};

#endif


