#ifndef ERRORCODE_H

#define  ERRORCODE_H

//EMV2 Kernel error codes 
#define EMVERR_GENERAL_BASE						0xF100
#define EMVERR_TRANSACTION_TYPE_NOT_SUPPORT		EMVERR_GENERAL_BASE+1
#define EMVERR_INVALID_PARAMETER				EMVERR_GENERAL_BASE+2
#define EMVERR_MAJOR_CONFIG_SETTING				EMVERR_GENERAL_BASE+3
#define EMVERR_USER_CANCEL						EMVERR_GENERAL_BASE+4
#define EMVERR_ICC_COMM_ERROR					EMVERR_GENERAL_BASE+5
#define EMVERR_CB_NOTSET						EMVERR_GENERAL_BASE+6
#define EMVERR_TAG_NOSUPPORTED					EMVERR_GENERAL_BASE+7

#define EMVERR_INDEX_BASE						0xF500
#define EMVERR_INVALID_RSPDATA					EMVERR_INDEX_BASE
#define EMVERR_UNSUFFICIENTDATA					EMVERR_INDEX_BASE+1
#define EMVERR_INVALID_TLV						EMVERR_INDEX_BASE+2
#define EMVERR_STOP_TRANSACTION					EMVERR_INDEX_BASE+3
#define EMVERR_DATA_MISSING						EMVERR_INDEX_BASE+4
#define EMVERR_CARD_BLOCK						EMVERR_INDEX_BASE+5
#define EMVERR_NOSUPPORT_CARDAID				EMVERR_INDEX_BASE+6
#define EMVERR_INVALIDPARAMETER					EMVERR_INDEX_BASE+7
#define EMVERR_GENERATEAC_WRONG					EMVERR_INDEX_BASE+8
#define EMVERR_FRAUDCARD_DATA					EMVERR_INDEX_BASE+9
#define EMVERR_MISS_ADFNAME						EMVERR_INDEX_BASE+10		
#define EMVERR_MISS_APLABEL						EMVERR_INDEX_BASE+11
#define EMVERR_DATA_EXIST						EMVERR_INDEX_BASE+12
#define EMVERR_FILE_NOTFOUND					EMVERR_INDEX_BASE+13
#define EMVERR_RECORD_NOTFOUND					EMVERR_INDEX_BASE+14
#define EMVERR_DATAPARENT_NULL					EMVERR_INDEX_BASE+15
#define EMVERR_CMD_NOTALLOWED					EMVERR_INDEX_BASE+16
#define EMVERR_APPLICATION_BLOCKED				EMVERR_INDEX_BASE+17
#define EMVERR_SCRIPT_FALIED					EMVERR_INDEX_BASE+18
#define EMVERR_SCRIPT_NOTPERFORMED				EMVERR_INDEX_BASE+19
#define EMVERR_KEYVERIFY_FAILED					EMVERR_INDEX_BASE+20
#define EMVERR_APPLICATION_NOTSUPPORT			EMVERR_INDEX_BASE+21

// EMV DATA ACCESS ERROR
#define DATA_INSUFFICIENT_BUFFER				EMVERR_INDEX_BASE+50
#define DATA_INVALID_TLV						EMVERR_INDEX_BASE+51
#define DATA_INVALIDE_TYPE						EMVERR_INDEX_BASE+52
#define DATA_INVALID_PROFILE					EMVERR_INDEX_BASE+53
#define DATA_PROFILE_INVALID_TLV				EMVERR_INDEX_BASE+54
#define DATA_FILE_NO_EXIST						EMVERR_INDEX_BASE+55
#define DATA_SYS_GETLASTERROR					EMVERR_INDEX_BASE+56
#define DATA_NO_EXIST							EMVERR_INDEX_BASE+57
#define DATA_SAVE_FAILED						EMVERR_INDEX_BASE+58
#define DATA_NOICS								EMVERR_INDEX_BASE+59
#define DATA_NOTM								EMVERR_INDEX_BASE+60
#define DATA_NOKEY								EMVERR_INDEX_BASE+61
#define DATA_NOAPP								EMVERR_INDEX_BASE+62

// EMV APPLICATION SPECIFIC ERROR
#define EMVERR_NOT_ACCEPTED  EMVERR_INDEX_BASE+70
#endif
